# Generated by Django 5.0.6 on 2024-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcorzina', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='categoru',
            field=models.CharField(blank=True, choices=[(1, 'Продукты'), (2, 'Лекарства'), (3, 'Одежда'), (4, 'Посуда')], max_length=100, null=True),
        ),
    ]
