# Generated by Django 5.0.6 on 2024-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcorzina', '0004_tovar_categoru'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='appcorzina.tovar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В сборке.', 'В сборке.'), ('В пути.', 'В пути.'), ('Доставлен.', 'Доставлен.')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='categoru',
            field=models.CharField(blank=True, choices=[('П', 'Продукты'), ('Л', 'Лекарства'), ('О', 'Одежда'), ('По', 'Посуда')], max_length=100, null=True),
        ),
    ]
